FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./

RUN npx prisma generate

EXPOSE 5555

# Запускаем studio с указанием на БД в volume
CMD ["npx", "prisma", "studio", "--port", "5555", "--browser", "none"]
